apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vmdb-rhel-skupper-service-bind
  annotations:
    github.com/project-slug: backstage-skupper-demo/backstage-catalog
spec:
  type: skupper-service-bind
  lifecycle: unknown
  owner: Joshua Mathianas
