apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-a-deployment-skupper-expose
  annotations:
    github.com/project-slug: backstage-skupper-demo/backstage-catalog
spec:
  type: skupper-expose
  lifecycle: unknown
  owner: Joshua Mathianas
