kind: ConfigMap
apiVersion: v1
metadata:
  name: vmdb-rhel-service-bind-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            192.168.23.4:
              platform: "podman"
              services:
                vmdb:
                  ports:
                    - 5432
                  targets:
                    - type: "host"
                      name: "192.168.23.4"
                  hostIp: ""
                  hostPorts:
                    - 5432:5432
          vars:
            ansible_user: cloud-user
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vmdb-rhel-service-bind
  namespace: backstage
spec:
  selector: {}
  template:
    metadata:
      name: vmdb-rhel-service-bind
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: {{ .Values.ansible.image }}
          command:
            - sh
            - -c
            - cp /workspace/.ssh/id_rsa /tmp/id_rsa && chmod 0400 /tmp/id_rsa && ansible-playbook /site-creation.yaml -i /workspace/source/inventory.yml -e vault_url=$(VAULT_URL) -e podman=true --private-key=/tmp/id_rsa
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
            - name: ssh
              mountPath: /workspace/.ssh/id_rsa
              subPath: id_rsa
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: vmdb-rhel-service-bind-inventory
          defaultMode: 420
      - name: ssh
        secret:
          secretName: ssh-key
          defaultMode: 256
      restartPolicy: Never
