kind: ConfigMap
apiVersion: v1
metadata:
  name: app-b-deployment-expose-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            proj2:
              ansible_connection: local
              namespace: skupper-proj2
              services:
                app-b:
                  ports:
                    - 8080
                  targets:
                    - type: "deployment"
                      name: app-b
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app-b-deployment-expose
  namespace: backstage
spec:
  selector: {}
  template:
    metadata:
      name: app-b-deployment-expose
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: {{ .Values.ansible.image }}
          command:
            - sh
            - -c
            - cp /workspace/.ssh/id_rsa /tmp/id_rsa && chmod 0400 /tmp/id_rsa && ansible-playbook /service.yaml -i /workspace/source/inventory.yml -e vault_url=$(VAULT_URL) -e podman=true --private-key=/tmp/id_rsa
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
            - name: ssh
              mountPath: /workspace/.ssh/id_rsa
              subPath: id_rsa
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: app-b-deployment-expose-inventory
          defaultMode: 420
      - name: ssh
        secret:
          secretName: ssh-key
          defaultMode: 256
      restartPolicy: Never
