kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: skupper-proj2
  # annotations:
  #   "helm.sh/hook": "pre-install"
spec: {}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: skupper-proj2-backstage-pipeline
  namespace: skupper-proj2
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
