kind: ConfigMap
apiVersion: v1
metadata:
  name: test202-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            
          vars:
            ansible_user: cloud-user
            vm_name: 
            aaphost: 
            template_id: 
            aaptoken: 
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test202-baremetal-openshift
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: baremetal-openshift
spec:
  selector: {}
  template:
    metadata:
      name: test202-baremetal-openshift
      labels:
        backstage.io/kubernetes-id: baremetal-openshift
    spec:
      serviceAccountName: pipeline
      containers:
        - name: baremetal-openshift-ansible
          image: {{ .Values.ansible.image }}
          command:
            - sh
            - -c
            - ansible-playbook /launch_job_template.yml -i /workspace/source/inventory.yml 
            - -e vm_name= 
            - -e aaphost=
            - -e template_id= 
            - -e aaptoken=
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
      volumes:
      - name: inventory
        configMap:
          name: test202-inventory
          defaultMode: 420
      restartPolicy: Never
